# Generated by Django 4.0 on 2024-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
