# Generated by Django 4.0 on 2024-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_group_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='visibility',
        ),
        migrations.AddField(
            model_name='group_student',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
